# Generated by Django 4.0.5 on 2022-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('editor', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_insta', models.CharField(default='simply._.shailesh', max_length=200)),
                ('user_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('user_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', models.TextField()),
                ('sub_head_1', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_head_1_top', models.TextField(blank=True, null=True)),
                ('sub_head_1_img', models.ImageField(blank=True, null=True, upload_to='custom/')),
                ('sub_head_1_bottom', models.TextField(blank=True, null=True)),
                ('sub_head_2', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_head_2_top', models.TextField(blank=True, null=True)),
                ('sub_head_2_img', models.ImageField(blank=True, null=True, upload_to='custom/')),
                ('sub_head_2_bottom', models.TextField(blank=True, null=True)),
                ('sub_head_3', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_head_3_top', models.TextField(blank=True, null=True)),
                ('sub_head_3_img', models.ImageField(blank=True, null=True, upload_to='custom/')),
                ('sub_head_3_bottom', models.TextField(blank=True, null=True)),
                ('sub_head_4', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_head_4_top', models.TextField(blank=True, null=True)),
                ('sub_head_4_img', models.ImageField(blank=True, null=True, upload_to='custom/')),
                ('sub_head_4_bottom', models.TextField(blank=True, null=True)),
                ('sub_head_5', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_head_5_top', models.TextField(blank=True, null=True)),
                ('sub_head_5_img', models.ImageField(blank=True, null=True, upload_to='custom/')),
                ('sub_head_5_bottom', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
