# Generated by Django 4.0.5 on 2022-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_delete_addpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_bg',
            field=models.ImageField(blank=True, null=True, upload_to='custom/'),
        ),
    ]
